import cls from "./styles.module.scss";

function TestOperation() {
    let str = '             <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;1. Fayl terminiga to&rsquo;gri ta&rsquo;rif berilgan javobni toping.</span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;A. bir xil tuzilishga ega bo&lsquo;lgan yozuvlar majmuasi ko&lsquo;rinishida tashkil etilgan ma&rsquo;lumotlar to&lsquo;plamidir;</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;B. har xil tuzilishga ega bo&lsquo;lgan yozuvlar majmuasi ko&lsquo;rinishida tashkil etilgan ma&rsquo;lumotlar to&lsquo;plamidir;</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;C. bir xil tuzilishga ega bo&lsquo;lgan videolar majmuasi ko&lsquo;rinishida tashkil etilgan ma&rsquo;lumotlar bazasi;</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;D. turli xil tuzilishga ega bo&lsquo;lgan yozuvlar dasturlari ko&lsquo;rinishida tashkil etilgan ma&rsquo;lumotlar oqimi</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">2. Zamonaviy operatsion tizimlarning asosiy tashkil etuvchilari qaysilar?</span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;A. yadro, kiritish-chiqarish tizimi, komanda protsessori, fayl tizimi;</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;B. printer, kiritish-chiqarish tizimi, speaker, fayl tizimi;</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;C. sichqoncha, kiritish-chiqarish tizimi, fayl tizimi;</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;D. xotira qurilmalari, komanda protsessori, fayl tizimi, dasturlar</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">3. Zamonaviy operatsion tizimlarda yadro qaysi asosiy funksiyalarni o\'zaro ta&rsquo;minlaydi?</span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;A. masalalar va resurslarni boshqarish, sinxronlashtirish va o&lsquo;zaro bog&lsquo;lanishi;</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;B. fayllar va resurslarni boshqarish, sinxronlashtirishni;</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;C. qurilmalar va resurslarni boshqarish, o&lsquo;zaro bog&lsquo;lanishini;</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;D. dasturlar masalalar va tarmoqlarni boshqarish, sinxronlashtirishni.</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">4. Tashqi qurilmalar bilan ma&rsquo;lumotlarni kiritish va chiqarish masalasini ta&rsquo;minlaydigan tizimlar qaysi qatorda to\'g\'ri ko\'rsatilgan?</span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;A. Kiritish va chiqarish tizimlari;</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;B. Chop etish va o&lsquo;chirish tizimi;</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;C. Sozlash va chiqarish tizimi;</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;D. Fayl va sinxronlash tizimi.</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">5. Hisoblash tizimlarini rivojlanishi bosqichlarini ko&lsquo;rib chiqib, biz rivojlanish jarayonida mumtoz (klassik) operatsion tizimlar bajargan qaysi asosiy funksiyalarni ajratishimiz mumkin?</span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;A. Topshiriqlarni rejalashtirish va protsessordan foydalanish;</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;B. Dasturlarni kommunikatsiya va sinxronizatsiya vositalari bilan ta&rsquo;minlash;</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;C. Xotirani boshqarish;</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;D. Barcha javoblar to&rsquo;g&rsquo;ri</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: D</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">6. Tarmoqdagi har bir mashina, kompyuterning avtonom operatsion tizimidan tarmoqda ishlashga imkon beradigan qo&lsquo;shimcha vositalarga ega bo&lsquo;lgan, qanday&nbsp; operatsion tizimini bajaradi?</span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. lokal operatsion tizimini</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B. global operatsion tizimini</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C. fizik operatsion tizimini</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. ierarxik&nbsp; operatsion tizimini</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">7. To\'g\'ri javobni belgilang.&nbsp; &hellip;. foydalanuvchilar uchun ham, bajariluvchi ilovalar uchun ham interfeysni tashkil etadi?</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. Operatsion tizim</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B. Apparat ta&rsquo;minoti</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C. Fayl tizimi</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. Matn muxarrirlari</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">8. Operatsion tizimning asosiy funksiyasiyalari nima?</span></strong><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. Foydalanuvchidan ma&rsquo;lum tilda tuzilgan komanda yoki topshiriqlarni qabul qilish va ularga ishlov berish.</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B.So&rsquo;rovlar ma&rsquo;lum tilda tuzilgan komanda yoki topshiriqlarni qabul qilish </span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C. Foydalanuvchidan fayllarni ajratib olish</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. Dasturiy ta&rsquo;minotchidan ma&rsquo;lum tilda tuzilgan komanda yoki topshiriqlarni yuklab olish</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">9. Autentifikatsiyaga to\'g\'ri ta\'rif bering.</span></strong><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. foydalanuvchi nomi va parolini qayd yozuvidagi qiymatga mosligini tekshirish.</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B. foydalanuvchi soni va parolini qayd yozuvidagi qiymatga mosligini oshirish</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C.dastur nomi va parolini qayd yozuvidagi qiymatga o&rsquo;zgartirish</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. to&rsquo;g&rsquo;ri javob yo&rsquo;q</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">10. Kim tomonidan dastlabki raqamli dasturlashtiriladigan kompyuter ixtiro qilingan?</span></strong><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. Charlz Bebich</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B. Alan Smith</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C. Kane Campbel</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. Chris Dawson</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">11. Operatsion tizimlarning rivojlanishida birinchi davrni qaysi yillar o&rsquo;z ichiga oladi?</span></strong><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. 1945-1955 yillar</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B. 1955-1965 yillar</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C. 1965-1980 yillar</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. 1980 yildan hozigacha bo&rsquo;lgan davr</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">12. Operatsion tizimlarning rivojlanishida ikkinchi davrni qaysi yillar o&rsquo;z ichiga oladi?</span></strong><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. 1945-1955 yillar</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B. 1955-1965 yillar</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C. 1965-1980 yillar</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. 1980 yildan hozigacha bo&rsquo;lgan davr</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: B</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">13. Operatsion tizimlarning rivojlanishida uchinchi davrni qaysi yillar o&rsquo;z ichiga oladi?</span></strong><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. 1945-1955 yillar</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B. 1955-1965 yillar</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C. 1965-1980 yillar</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. 1980 yildan hozigacha bo&rsquo;lgan davr</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: C</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">14. Operatsion tizimlarning rivojlanishida tortinchi davrni qaysi yillar o&rsquo;z ichiga oladi?</span></strong><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. 1945-1955 yillar</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B. 1955-1965 yillar</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C. 1965-1980 yillar</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. 1980 yildan hozigacha bo&rsquo;lgan davr</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: D</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">15. Hisoblash tizimi dastlabki yillarda bir vaqtning o&lsquo;zida faqat bitta operatsiyani bajargan. Ya&rsquo;ni qaysi operatsiyani?</span></strong><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. kiritish-chiqarish</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B.yuklab olish &ndash;o&rsquo;chirib tashlash</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C.nusxa olish-chiqarish</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. rangini o&rsquo;zgartirish-chiqarish</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">16. 1951-1952 yillarqaysi&nbsp; qaysi simvolli tillardan birinchi kompilyatorlar versiyalari yuzaga keldi?</span></strong><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. Fortran</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B. CSS</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C. Go</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. Dropal</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">17. 1954 yili&nbsp; IBM-701 uchun qaysi til ishlab chiqildi?</span></strong><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. Assembler</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B.Java Script</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C.Java</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. C++</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">18. Birinchi lampali mashinalar qachon yaratildi?</span></strong><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. 1940 yillar o&lsquo;rtalarida</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B. 1740 yillar o&lsquo;rtalarida</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C. 1840 yillar o&lsquo;rtalarida</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. 1900 yillar o&lsquo;rtalarida</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">19. Tarif qaysi termin haqida ketayotganligini aniqlang? &hellip;&hellip;&hellip;.&ndash; bu hisoblash jarayonning tashkil qilish usuli bo&lsquo;lib, bitta protsessorda navbat bilan bir nechta dastur bajariladi?</span></strong><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. Multidasturlash</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B. Nusxa olish</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C. Ma&rsquo;lumot yuborish</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. Malumot qabul qilib olish</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">20. Multidasturlashning asosiy hususiyatlarini tog\'ri belgilang.</span></strong></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;A. Barcha javoblar to&rsquo;g&rsquo;ri</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;B. Ximoya mexanizmini amalga oshirish.</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;C. Uzilishlar mavjudligi.</span><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;"> </span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">&nbsp;&nbsp;&nbsp;D. Arxitekturada parallelizmni rivojlantirish</span></p>\n' +
        '            <p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size: 13pt; font-family: Calibri, sans-serif; color: #000000;">ANSWER: A</span></p>'
    return (
        <div>
            <h2 className={cls.title}>Test section </h2>
            <div dangerouslySetInnerHTML={{__html: str}}></div>

        </div>
    );
}

export default TestOperation;
