const syllabusData = [
  {
    title: "Java Dasturlash tili",
    otm: "Toshkent Davlat Iqtisodiyot Universiteti",
    teacher: "Zoirov Ulmas",
    email: "zoirov.ulmas@tsue.uz",
    kafedra: "Raqamli iqtisodiyot va Axborot Texnologiyalari",
    direction: "Axborot texnologiyalari",
    course: "3",
    language: "O'zbekcha",
    path: "java",
    childPath: "about-java",
  },
  {
    title: "Operatsion Tizimlar",
    otm: "Toshkent Davlat Iqtisodiyot Universiteti",
    teacher: "Abdulaxatov Muzzafar",
    email: "abdulaxatov.muzzafar@tsue.uz",
    kafedra: "Raqamli iqtisodiyot va Axborot Texnologiyalari",
    direction: "Axborot texnologiyalari",
    course: "3",
    language: "O'zbekcha",
    path: "operation",
    childPath: "about-operation",
  },
  {
    title: "Elektron hukumat ",
    otm: "Toshkent Davlat Iqtisodiyot Universiteti",
    teacher: "Rajabov Sherzod",
    email: "rajabov.sherzod@gmail.com",
    kafedra: "Raqamli iqtisodiyot va Axborot Texnologiyalari",
    direction: "Raqamli Iqtisotiyot",
    course: "3",
    language: "Ingliz",
    path: "government",
    childPath: "about-government",
  },
  {
    title: "Biznes Axborot Texnologiyalari",
    otm: "Toshkent Davlat Iqtisodiyot Universiteti",
    teacher: "Abdullayev Munis",
    email: "abdullayev.munis@tsue.uz",
    kafedra: "Raqamli iqtisodiyot va Axborot Texnologiyalari",
    direction: "abdullayev.munis@tsue.uz",
    course: "3",
    language: "O'zbekcha",
    path: "social",
    childPath: "about-social",
  },
];

export default syllabusData;
