// qisqa kalit rfce

import cls from "./styles.module.scss";
// style ulash

function AboutCourseGovernment() {
  return (
    <div>
              <h1 className={cls.title}>About course</h1>
              <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">INFORMATION ABOUT SUBJECT</span></strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&nbsp;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Subject cipher: </span><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">EGOVERN6</span></strong></p>
        <p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Subject name:&nbsp; </span><strong><span style="font-size: 14pt; font-family: 'Times New Roman'; color: #000000;">ELECTRONIC GOVERNMENT&nbsp;</span></strong></p>
        <p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Term/year</span><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">: 5-term/ 2022-2023 academic year (election subject)</span></strong></p>
        <p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Department:</span><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;"> Digital economy and information technologies</span></strong></p>
        <p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Hours/ amount of credits:&nbsp; </span><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">6 ECTS (72 auditorium hours)</span></strong></p>
        <p>&nbsp;</p>
        <p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Sessions according to the course:&nbsp;</span></strong></p>
        <p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Classroom time: According to the schedule</span></p>
        <p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Requirements:&nbsp;</span></p>
        <p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Responsible department for the course: Department of</span><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;"> </span></strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Digital economy and information technologies</span></p>
        <p>&nbsp;</p>
        <p style="line-height: 1.8; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 15pt; font-family: 'Times New Roman'; color: #000000;">Instructor information</span></strong></p>
        <p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Instructors: A.A.Abidov, S.S.Qulmatova, M.M. Abdulakhatov,&nbsp;&nbsp;</span></p>
        <p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Location of the department: TSUE, 5 educational building, 105 auditorium</span></p>
        <p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Phone: 71-239-28-41 office phone</span></p>
        <p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Email: </span><a style="text-decoration: none;" href="mailto:Abidov53@bk.ru"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #0000ff; text-decoration: underline; text-decoration-skip-ink: none;">Abidov53@bk.ru</span></a><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">, </span><a style="text-decoration: none;" href="mailto:squlmatova@tsue.uz"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #0000ff; text-decoration: underline; text-decoration-skip-ink: none;">squlmatova@tsue.uz</span></a><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #0000ff; text-decoration: underline; text-decoration-skip-ink: none;">,</span><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #0000ff;"> </span><a style="text-decoration: none;" href="mailto:muzaffar.abdulakhatov@gmail.com"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #0000ff; text-decoration: underline; text-decoration-skip-ink: none;">muzaffar.abdulakhatov@gmail.com</span></a><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&nbsp;</span></p>
        <p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Hours: By appointment&nbsp;</span></p>
        <p><br /><br /></p>
        <ol style="margin-top: 0px; margin-bottom: 0px; padding-inline-start: 48px;">
        <li style="list-style-type: upper-roman; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; font-weight: bold; margin-left: 10.35pt;">
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 13pt;">Course description</span></strong></p>
        </li>
        </ol>
        <p style="line-height: 1.2; text-indent: 28.35pt; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">This subject is the central fundamental part of ICT in the economy and is taught in the first semester of the third year.</span></p>
        <p style="line-height: 1.2; text-indent: 28.35pt; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">The role of modern information and communication technologies in developing the electronic government system; Stages of development of the electronic government system in the Republic of Uzbekistan, current status, and plans; will be introduced. The government portal of the Republic of Uzbekistan (<a href="www.gov.uz" aria-invalid="true">www.gov.uz</a>), "Uniform Interactive State Services" and Open Information Portals of the Republic of Uzbekistan, as well as the purpose and tasks of the "Development of the Electronic Government System" center; An understanding of "electronic government" is provided. Bodies carrying out state regulation of the field of "electronic government" and their powers; the rights of individuals and legal entities to use the electronic government system; "Electronic government" architecture and forms of interaction; Real cases of ensuring the confidentiality of information resources in the "Electronic Government" system are also analyzed. In the "Electronic Government" system, students will learn about innovative technologies, foreign experiences in creating an electronic government system, and their measures and projects to create complex electronic government systems, databases, and information systems electronic government systems.</span></p>
        <p style="line-height: 1.2; text-indent: 28.35pt; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">The government portal of the Republic of Uzbekistan (<a href="www.gov.uz" aria-invalid="true">www.gov.uz</a>), "Uniform Interactive State Services" and Open Data portals of the Republic of Uzbekistan will be taught using information and communication technologies. Working with modern technology and software tools; Working on the "Uniform Interactive State Services" portal, creating and editing electronic documents; They will have comprehensive knowledge of the culture of communicating and exchanging information on the Internet, using the database of the electronic government system.</span></p>
        <p><br /><br /><br /></p>
        <ol style="margin-top: 0px; margin-bottom: 0px; padding-inline-start: 48px;">
        <li style="list-style-type: upper-roman; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; font-weight: bold; margin-left: 10.35pt;">
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 13pt;">The purpose of course</span></strong></p>
        </li>
        </ol>
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull;&nbsp; The purpose of this subject is to teach students how to make effective decisions in an enterprise or any other organization using the methodology of creating, sharing, analyzing, storing, and collecting information for the effective implementation of business processes.</span></p>
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">Objectives enable students to learn:</span></p>
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; demonstrate independent thinking;</span></p>
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; preparation for independent work;</span></p>
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; correct modelling of situations taking into account the technological, situational, organizational-legal, and institutional features of electronic government and digital economy;</span></p>
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; to understand the infrastructure of electronic government, and the nature of digital technologies;</span></p>
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; introduction of electronic government and modern technologies, development of the digital economy under the conditions of public-private partnership;</span></p>
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; to determine the positive and negative consequences of electronic government and digital transformation, and the factors affecting them;</span></p>
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; assessment of the impact of the digital economy on macro- and micro-level indicators; evaluation of the effectiveness of digital transformation;</span></p>
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; identification of cyber security problems, development of a digital economy based on public-private partnership;</span></p>
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; to identify and evaluate the factors affecting the effective organization of business processes;</span></p>
        <p style="line-height: 1.295; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; to acquire the skills of effective use of e-commerce models.</span></p>
        <p>&nbsp;</p>
        <p style="line-height: 1.2; text-indent: 35.45pt; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">III.&nbsp;Learning Outcomes</span></strong></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; demonstrates knowledge and understanding of e-government concepts, digital technologies, and e-commerce;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; studies the laws of e-government development, business models in e-government, and digital platforms;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; can analyze the theoretical and methodological aspects of e-government and digital business, organization of e-government and digital country building, and growth factors of the IT industry;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; e-government analyzes and interprets development processes;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; analyzes e-government development programs in different countries;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; can describe the impact of electronic government on economic development;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; analyzes the uniqueness and basic principles of management in electronic government;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; Calculates the assessment of electronic government indicators;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; Distinguish between the business theoretical and methodological aspects of e-government and digitization.</span></p>
        <p>&nbsp;</p>
        <p style="line-height: 1.2; text-indent: 28.35pt; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">IV. Teaching methods:</span></strong></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; implementation of practical work based on the real situation;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; writing essays, theses and articles;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; solving situational tasks (case studies);</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; process-oriented education;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; participate in discussions;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; work in small groups;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; project work;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; independent work;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; preparation of presentations;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; solve different levels of tests;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; conducting surveys;</span></p>
        <p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000;">&bull; problem solving.</span></p>
        <p><br /><br /><br /><br /><br /></p>
    </div>
  );
}
export default AboutCourseGovernment;
